name: analyzerutils
version: 0.0.1
description: Dart analyzer utilities.

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  ansicolor: ">=0.0.9 <0.1.0"
  barback: any
  dart_style: any
  args: any
  code_transformers: any
  args: "^0.13.2"
  analyzer: "^0.27.3"
  path: "^1.3.6"
  async_await:
      git: https://github.com/algobardo/async_await_transformer_deprecated.git
  yaml: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
executables:
  analyzerutils:
